<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Hopstarter-Book-Things-Book.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\Montserrat-Black.ttf" />
    <None Remove="Assets\Fonts\Montserrat-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-Bold.ttf" />
    <None Remove="Assets\Fonts\Montserrat-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\Montserrat-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\Montserrat-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-Italic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-Light.ttf" />
    <None Remove="Assets\Fonts\Montserrat-LightItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-Medium.ttf" />
    <None Remove="Assets\Fonts\Montserrat-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-Regular.ttf" />
    <None Remove="Assets\Fonts\Montserrat-SemiBold.ttf" />
    <None Remove="Assets\Fonts\Montserrat-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Montserrat-Thin.ttf" />
    <None Remove="Assets\Fonts\Montserrat-ThinItalic.ttf" />
    <None Remove="Assets\Images\adminbackground.png" />
    <None Remove="Assets\Images\ask-question.png" />
    <None Remove="Assets\Images\attendance.png" />
    <None Remove="Assets\Images\Attendifysplah.png" />
    <None Remove="Assets\Images\bb2.png" />
    <None Remove="Assets\Images\darkgreen2.png" />
    <None Remove="Assets\Images\darkgrenn.png" />
    <None Remove="Assets\Images\landing.jpg" />
    <None Remove="Assets\Images\login.png" />
    <None Remove="Assets\Images\logo.png" />
    <None Remove="Assets\Images\stats.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Hopstarter-Book-Things-Book.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
  </ItemGroup>
	
<ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc6.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.2-preview.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
    <PackageReference Include="Supabase" Version="1.1.1" />
    <PackageReference Include="Supabase.Gotrue" Version="6.0.3" />
</ItemGroup>
	
<ItemGroup>
  <ProjectReference Include="..\Attendify.DATA\Attendify.DATA.csproj" />
</ItemGroup>


  <ItemGroup>
    <Resource Include="Assets\Fonts\Montserrat-Black.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-BlackItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Bold.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-BoldItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-ExtraBold.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-ExtraBoldItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-ExtraLight.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-ExtraLightItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Italic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Light.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-LightItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Medium.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-MediumItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Regular.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-SemiBold.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-SemiBoldItalic.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Thin.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-ThinItalic.ttf" />
    <Resource Include="Assets\Images\adminbackground.png" />
    <Resource Include="Assets\Images\ask-question.png" />
    <Resource Include="Assets\Images\attendance.png" />
    <Resource Include="Assets\Images\Attendifysplah.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\bb2.png" />
    <Resource Include="Assets\Images\darkgreen2.png" />
    <Resource Include="Assets\Images\darkgrenn.png" />
    <Resource Include="Assets\Images\landing.jpg" />
    <Resource Include="Assets\Images\login.png" />
    <Resource Include="Assets\Images\logo.png" />
    <Resource Include="Assets\Images\stats.png" />
  </ItemGroup>


  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
