; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Attendify"
#define MyAppVersion "1.1"
#define MyAppPublisher "IT Group4, C#"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "Attendify.UI.exe"
#define MyApiExeName "Attendify.API.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DDCF777C-ACDF-477A-AE34-9CD8BAD2740F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\UI\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=attendifyssetup
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Deployment: Separate directories to prevent DLL conflicts
Source: "Publish\UI\*"; DestDir: "{app}\UI"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "Publish\API\*"; DestDir: "{app}\API"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Shortcuts must point to the UI executable in the UI subdirectory
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\UI\{#MyAppExeName}"; WorkingDir: "{app}\UI"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\UI\{#MyAppExeName}"; Tasks: desktopicon; WorkingDir: "{app}\UI"

[Run]
; Start API silently in background (from API subdirectory)
Filename: "{app}\API\{#MyApiExeName}"; Flags: nowait runhidden

; Start UI normally (from UI subdirectory)
Filename: "{app}\UI\{#MyAppExeName}"; Flags: nowait
